openapi: 3.2.0
info:
  title: Palmistry Service Prediction API
  description: API for Palmistry Service - AI Power Palm Reading
  version: 1.0.0
tags:
- name: Prediction
paths:
  /predict:
    post:
      tags:
      - Prediction
      summary: Predict Base64
      operationId: predict_base64_predict_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictRequestBase64'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/predict:
    post:
      tags:
      - Prediction
      summary: Api Predict Url
      operationId: api_predict_url_api_predict_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictRequestUrl'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /palmistry/get-palm-image:
    post:
      tags:
      - Prediction
      summary: Api Processed Palm
      operationId: api_processed_palm_palmistry_get_palm_image_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PredictRequestPalmID'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    PredictRequestBase64:
      properties:
        image_url:
          type: string
          title: Image Url
      type: object
      required:
      - image_url
      title: PredictRequestBase64
    PredictRequestUrl:
      properties:
        url:
          anyOf:
          - type: string
          - type: 'null'
          title: Url
        image_url:
          anyOf:
          - type: string
          - type: 'null'
          title: Image Url
      type: object
      title: PredictRequestUrl
    PredictRequestPalmID:
      properties:
        palm_id:
          type: string
          title: Palm Id
      type: object
      required:
      - palm_id
      title: PredictRequestPalmID
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
